spring:
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: admin
    password: root
    properties:
      schema: bootstrap

server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      hibernate:
        type: DEBUG
      springframework:
        r2dbc: DEBUG
      springdoc: DEBUG
    io:
      swagger: DEBUG

management:
  endpoint:
    health:
      group:
        custom:
          show-details: always
          show-components: always
          status.http-mapping.up: 207
  endpoints:
    web:
      exposure:
        include: "*"
